//go:build !ignore_autogenerated

/*
Copyright 2026 The ServiceSpread Scheduler Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpreadArgs) DeepCopyInto(out *ServiceSpreadArgs) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.RequirePolicy != nil {
		in, out := &in.RequirePolicy, &out.RequirePolicy
		*out = new(bool)
		**out = **in
	}
	out.FallbackCacheTTL = in.FallbackCacheTTL
	out.ReservationTTL = in.ReservationTTL
	out.ReconcilePeriod = in.ReconcilePeriod
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpreadArgs.
func (in *ServiceSpreadArgs) DeepCopy() *ServiceSpreadArgs {
	if in == nil {
		return nil
	}
	out := new(ServiceSpreadArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceSpreadArgs) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
