//go:build !ignore_autogenerated

/*
Copyright 2026 The ServiceSpread Scheduler Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpreadPolicy) DeepCopyInto(out *ServiceSpreadPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpreadPolicy.
func (in *ServiceSpreadPolicy) DeepCopy() *ServiceSpreadPolicy {
	if in == nil {
		return nil
	}
	out := new(ServiceSpreadPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceSpreadPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpreadPolicyList) DeepCopyInto(out *ServiceSpreadPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceSpreadPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpreadPolicyList.
func (in *ServiceSpreadPolicyList) DeepCopy() *ServiceSpreadPolicyList {
	if in == nil {
		return nil
	}
	out := new(ServiceSpreadPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceSpreadPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpreadPolicySpec) DeepCopyInto(out *ServiceSpreadPolicySpec) {
	*out = *in
	in.ServiceSelector.DeepCopyInto(&out.ServiceSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpreadPolicySpec.
func (in *ServiceSpreadPolicySpec) DeepCopy() *ServiceSpreadPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpreadPolicySpec)
	in.DeepCopyInto(out)
	return out
}
